# Generated by Django 5.2 on 2025-07-02 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#FF6B6B', help_text='Cor em formato hexadecimal', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('filme', 'Filme'), ('serie', 'Série')], default='filme', max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('video_url', models.URLField(help_text='URL do vídeo no Bunny.net')),
                ('duracao', models.CharField(blank=True, help_text='Ex: 2h 15min', max_length=20)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('classificacao', models.CharField(blank=True, help_text='Ex: 12, 16, 18', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False, help_text='Aparecer nos destaques')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='filmes.categoria')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
