# Generated by Django 5.2 on 2025-07-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('numero', models.IntegerField()),
                ('temporada', models.IntegerField(default=1)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episodios/')),
                ('video_url', models.URLField()),
                ('duracao', models.CharField(blank=True, max_length=20)),
                ('data_lancamento', models.DateField(blank=True, null=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='filmes.conteudo')),
            ],
            options={
                'verbose_name': 'Episódio',
                'verbose_name_plural': 'Episódios',
                'ordering': ['temporada', 'numero'],
            },
        ),
    ]
