# Generated by Django 5.2 on 2025-07-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='URL do trailer (opcional)', null=True),
        ),
    ]
